version: 0
verbose: false
mounts:
- !mounts.SSHCode &code_mount_parkour
  local_path: ../parkour
  local_tar: /tmp/{now:%Y-%m-%d}/{now:%H%M%S.%f}-parkour.tar
  host_path: "{secret.JYNS_HOME}/jaynes_mount/parkour/{now:%Y-%m-%d}/{now:%H%M%S.%f}-parkour"
  remote_tar: "{secret.JYNS_HOME}/jaynes_mount/parkour/{now:%Y-%m-%d}/{now:%H%M%S.%f}-parkour.tar"
  pypath: true
  excludes: >-
    --exclude='samples' --exclude='images' --exclude='videos' --exclude='datasets'
    --exclude='figures' --exclude='results' --exclude='analysis' --exclude='*.ipynb'
    --exclude='*__pycache__' --exclude='*.git'  --exclude='*.gif'
    --exclude='*.mp4' --exclude='*.idea' --exclude='*.egg-info' --exclude='*.pkl'
    --exclude='*/logs/*'
    --exclude="*.cache"
    --exclude='assets/robots/anymal_b'
    --exclude='assets/robots/anymal_c'
    --exclude='assets/robots/cassie'
  compress: true
runners:
  - !runners.Simple &ssh_runner
    name: "parkour-{now:%H%M%S}-{RUN.count}"
    # can use either /bin/sh, or /bin/bash --norc. Somehow making the
    # process background affects the envs, even though the ~/.profile,
    # ~/.bashrc, ~/.bash_profile are never sourced. Adding debugging
    # printouts, even before the interactive break point, yiels no stdout
    # output.
    shell: "screen -dm /bin/bash --norc"
    setup: |
      echo '{secret.JYNS_PASSWORD}' | renew
      source $HOME/.jaynes_bash
      conda activate parkour
      echo running inside `hostname`
      export MUJOCO_GL=egl
      export CUDA_LAUNCH_BLOCKING=1
    envs: LANG=utf-8 LC_CTYPE=en_US.UTF-8
    pypath: "{mounts[0].host_path}"
    work_dir: "{mounts[0].host_path}"
run:
  mounts:
  - *code_mount_parkour
  runner: *ssh_runner
  launch: !ENV
    type: ssh
    ip: "{secret.JYNS_HOST}"
    username: "{secret.JYNS_USERNAME}"
    password: "{secret.JYNS_PASSWORD}"
    launch_dir: "{secret.JYNS_HOME}/jaynes_mount/{now:%Y-%m-%d}/{now:%H%M%S.%f}"
