python stack.py --rollout=0 --stack_size=5
python stack.py --rollout=1 --stack_size=5
python stack.py --rollout=2 --stack_size=5
python stack.py --rollout=3 --stack_size=5
python stack.py --rollout=4 --stack_size=5
python stack.py --rollout=5 --stack_size=5
python stack.py --rollout=6 --stack_size=5
python stack.py --rollout=7 --stack_size=5
python stack.py --rollout=8 --stack_size=5
python stack.py --rollout=9 --stack_size=5
python stack.py --rollout=10 --stack_size=5
python stack.py --rollout=11 --stack_size=5
python stack.py --rollout=12 --stack_size=5
python stack.py --rollout=13 --stack_size=5
python stack.py --rollout=14 --stack_size=5
python stack.py --rollout=15 --stack_size=5
python stack.py --rollout=16 --stack_size=5
python stack.py --rollout=17 --stack_size=5
python stack.py --rollout=18 --stack_size=5
python stack.py --rollout=19 --stack_size=5
python stack.py --rollout=20 --stack_size=5
#python stack.py --rollout=21 --stack_size=5
#python stack.py --rollout=22 --stack_size=5
#python stack.py --rollout=23 --stack_size=5
#python stack.py --rollout=24 --stack_size=5
#python stack.py --rollout=25 --stack_size=5
#python stack.py --rollout=26 --stack_size=5
#python stack.py --rollout=27 --stack_size=5
#python stack.py --rollout=28 --stack_size=5
#python stack.py --rollout=29 --stack_size=5
#python stack.py --rollout=30 --stack_size=5
#python stack.py --rollout=31 --stack_size=5
#python stack.py --rollout=32 --stack_size=5
#python stack.py --rollout=33 --stack_size=5
#python stack.py --rollout=34 --stack_size=5
#python stack.py --rollout=35 --stack_size=5
#python stack.py --rollout=36 --stack_size=5
#python stack.py --rollout=37 --stack_size=5
#python stack.py --rollout=38 --stack_size=5
#python stack.py --rollout=39 --stack_size=5
#python stack.py --rollout=40 --stack_size=5
#python stack.py --rollout=41 --stack_size=5
#python stack.py --rollout=42 --stack_size=5
#python stack.py --rollout=43 --stack_size=5
#python stack.py --rollout=44 --stack_size=5
#python stack.py --rollout=45 --stack_size=5
#python stack.py --rollout=46 --stack_size=5
#python stack.py --rollout=47 --stack_size=5
#python stack.py --rollout=48 --stack_size=5
#python stack.py --rollout=49 --stack_size=5
